// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maakytyswcspthrnkfxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hYWt5dHlzd2NzcHRocm5rZnhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MjczOTMsImV4cCI6MjA2NjIwMzM5M30.5Pa44uEdyLjA7WhAbo1lv45JeKlf4mp8BaoDeck00Ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);